---
title: "Por definir xd"
author: "Contreras Valeria, Guillén David, Zamora Samuel, Morales Andrés"
date: "Junio del 2024"
output: 
  pdf_document:
    toc: TRUE
    toc_depth: 2
fontside: 11pt
lang: Es-es
---

```{r Bliblioteca, include=FALSE}
#Paquetes a utilizar
library(tinytex)
library(DBI)
library(RSQLite)
library(kableExtra)

#BBDD
futbol <- dbConnect(SQLite(), dbname = "Fútbol Europeo BBDD.sqlite")
print(futbol)

#Funciones
moda<- function(x) {
   return(as.numeric(names(which.max(table(x)))))
}


#Tablas de la BBDD
Divisiones <- dbGetQuery(futbol, "SELECT * FROM Divisiones")
Partidos <- dbGetQuery(futbol, "SELECT * FROM Partidos")
remove(Divisiones, Partidos)

#variables
Resumen1=list("N de Datos"=length, Min=min, Max=max, Moda=moda, Media=mean, Mediana=median, Desviación=sd)

v_ath_local <- dbGetQuery(futbol, 
"SELECT Team_Local, Ganador, count(Ganador) AS Frecuencia, Temporada 
  FROM Partidos 
	WHERE Cod_Division='SP1' AND Team_Local='Ath Bilbao'
	GROUP BY Ganador")
v_ath_visitante <- dbGetQuery(futbol, 
"SELECT Team_Visitante, Ganador, count(Ganador) AS Frecuencia, Temporada 
  FROM Partidos 
	WHERE Cod_Division='SP1' AND Team_Visitante='Ath Bilbao'
	GROUP BY Ganador")

#Para ultimo objetivo
#goles_athletic_local <- dbGetQuery(futbol, "SELECT * FROM laliga_2017_2018
#	WHERE Team_Local='Ath Bilbao'")
```

\pagebreak
# Planteamiento del Problema

 El fútbol es un deporte a nivel profesional alto de once jugadores por equipo, involucra la cooperación mutua del equipo y se sabe que es un deporte que conlleva el contacto. Estos equipos tienen la misión de trasladar un balón utilizando cualquier parte del cuerpo exceptuando brazos y manos con la finalidad de encajarlo dentro de la portería o arco del conjunto rival, acción que se denomina gol. El equipo con más goles durante un partido de 90 minutos ganará el encuentro.

 Pueden existir partidos en los que un equipo sea tácticamente muy superior al rival, o que cuente con jugadores de mejor calidad. Al final del partido puede influir en que dominen en estadísticas como mayor posesión de balón, mayor precisión en los pases, más disparos al arco rival, mayor cantidad de tiros libres y todo lo que pueda favorecer a un equipo para demostrar que es superior, pero lo único que sentencia un partido son los goles, y ganar como en cualquier deporte es la única manera de avanzar en un torneo o competición.

 Ya que marcar goles para cualquier equipo es una necesidad, resulta interesante develar qué factores pueden influir en los conjuntos para que aumente o disminuya su capacidad goleadora.

 Se tiene en estudio una base de datos relacionados a algunas ligas del fútbol europeo, entre ellas las 5 más importantes del mundo según la plataforma Global Football Rankings, que utiliza análisis de datos para evaluar y clasificar las ligas de fútbol en todo el mundo, esta plataforma concluye que en este top se encuentran la Premier League (Inglaterra), La Bundesliga (Alemania), LaLiga (España), Serie A (Italia) y Ligue 1 (Francia).  
 La base de datos cuenta con variables como los goles anotados por los equipos de cada liga tanto de local como de visitante, a lo largo de las temporadas que transcurrieron desde el año 2006 hasta el año 2021, y partiendo de dicha información surgen las interrogantes que se presentan a continuación. 

## Interrogantes/Objetivos

* ¿Los equipos tienden a ganar más cuando juegan en sus estadios locales?

* ¿Influyeron los partidos sin público durante la pandemia en la capacidad de anotar goles por parte de los equipos que jugaron de visitante?

* ¿Tuvo influencia la implementación del Video Assistant Referee (VAR), en la cantidad de goles que ofrecían las respectivas ligas?

* Si seguimos a un equipo en específico ¿se puede inferir la cantidad de goles que les será anotados en contra mientras vamos conociendo los goles que anoten?

# Estadística Descriptiva de la BBDD



# ¿Los equipos tienden a ganar más cuando juegan en sus estadios locales?

 Trabajaremos con una muestra de la BBDD, el equipo Atheltic Club de Bilbao es su temporada 2017-18 y 2018-19, en estas temporadas encontramos un par de características a resaltar, veamoslas paso a paso...

## Gráfico

# Bibliografía

1) https://www.transfermarkt.es/laliga/trainerwechsel/wettbewerb/ES1/plus/?saison_id=2018

2) https://www.transfermarkt.es/laliga/trainerwechsel/wettbewerb/ES1/plus/?saison_id=2017

3) https://www.transfermarkt.es/laliga/trainereffekt/wettbewerb/ES1/plus/?saison_id=2018&spiele=15
